services:
  postgres:
    image: postgres:latest
    container_name: postgres-1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydatabase